routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * FronEnd
 */
Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

/**
 * Unlock System
 */
Route::post('/login/locked', [App\Http\Controllers\Auth\LoginController::class, 'unlock'])
    ->name('login.unlock');

/**
 * Backend Routes
 */
Route::group(['middleware' => ['auth', 'check_user_status', 'check_user_single_session', 'auth.lock', '2fa', 'language']], function () {

    /**
     * Dashboard / Home
     */
    Route::get('/home', [App\Http\Controllers\Backend\HomeController::class, 'index'])
        ->name('home');

    /**
     * Lockscreen
     */
    Route::get('/login/locked', [App\Http\Controllers\Auth\LoginController::class, 'locked'])
        ->withoutMiddleware('auth.lock')->name('login.locked');

    /**
     * User
     */
    Route::controller(App\Http\Controllers\Backend\UserController::class)->group(function () {
        Route::prefix('users')->group(function () {
            Route::get('/', 'index')->name('users.index');
            Route::get('/create', 'create')->name('users.create');
            Route::get('/edit/{user}', 'edit')->name('users.edit');
            Route::post('/store', 'store')->name('users.store');
            Route::patch('/update/{user}', 'update')->name('users.update');
            Route::get('/getUsers', 'getUsers')->name('users.get');
            Route::get('/activate/{id}', 'active')->name('users.active');
            Route::get('/deactivate/{id}', 'deactive')->name('users.deactive');
        });
    });

    /**
     * Profile
     */
    Route::controller(App\Http\Controllers\Backend\ProfileController::class)->group(function () {
        Route::prefix('profile')->group(function () {
            Route::get('/{user}', 'user_profile')->name('user.profile');
            Route::patch('/my_profile/update/', 'update_my_profile')->name('profile.update');
        });
        Route::get('/lang/{language}', 'change_language')->name('lang.update');
        Route::get('/lockscreen', 'lockscreen')->name('users.lockscreen');
        Route::get('/my_profile/{user}', 'my_profile')->name('my.profile');
    });

    /**
     * System Settings
     */
    Route::controller(App\Http\Controllers\Backend\SystemSettingController::class)->group(function () {
        Route::prefix('system')->group(function () {
            Route::get('/settings', 'index')->name('system_settings');
            Route::get('/settings/edit', 'settings')->name('system_settings.edit');
            Route::post('/settings/edit', 'update')->name('system_settings.update');
        });
    });

    /**
     * Logs
     */
    Route::controller(App\Http\Controllers\Backend\LogController::class)->group(function () {
        Route::prefix('log')->group(function () {
            Route::get('/', 'index')->name('logs.index');
            Route::get('/getLogs', 'getLogs')->name('logs.get');
            Route::get('/clearLogs', 'clearLogs')->name('logs.clear');
        });
    });

    /**
     * 2FA
     */
    Route::controller(App\Http\Controllers\Backend\LoginSecurityController::class)->group(function () {
        Route::prefix('2fa')->group(function () {
            Route::any('/', 'show2faForm')->name('2fa');
            Route::post('/secret',  'generate2faSecret')->name('generate2faSecret');
            Route::post('/enable', 'enable2fa')->name('enable2fa');
            Route::post('/disable', 'disable2fa')->name('disable2fa');
        });
    });

    /**
     * Roles and permissions
     */
    Route::resource('/roles', App\Http\Controllers\RoleController::class);
    Route::resource('/permissions', App\Http\Controllers\PermissionController::class);

    /**
     * 2FA middleware
     */
    Route::post('/2faVerify', function () {
        return redirect(URL()->previous());
    })->name('2faVerify');
});

app/Http/Controllers/Backend/ProfileController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\ValidationException;
use App\Models\User;
use App\Traits\UploadTrait;
use RealRashid\SweetAlert\Facades\Alert;
use DataTables;
use Illuminate\Support\Facades\Hash;
use Spatie\Activitylog\Models\Activity;

class ProfileController extends Controller
{
    use UploadTrait;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth', '2fa']);
        $this->middleware('permission:profiles-view-all', ['only' => ['user_profile']]);
        $this->middleware('permission:profiles-view-own', ['only' => ['my_profile']]);
        $this->middleware('permission:profiles-edit-all', ['only' => ['update_user_profile']]);
        $this->middleware('permission:profiles-edit-own', ['only' => ['update_my_profile']]);
    }

    /**
     * Show auth user profile
     *
     * @return void
     */
    public function my_profile()
    {
        $languages = ([
            "en" => 'en',
            "pt_BR" => 'pt_BR'
        ]);

        $user = Auth::user();

        return view('backend.user.profile.my_profile', compact('user', 'languages'));
    }

    /**
     * Show profile of selected user
     *
     * @param User $user
     * @return void
     */
    public function user_profile(User $user)
    {
        $languages = ([
            "en" => 'en',
            "pt_BR" => 'pt_BR'
        ]);

        return view('backend.user.profile.user_profile', compact('user', 'languages'));
    }

    /**
     * Update user data
     *
     * @param User $user
     * @param UpdateUserRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function update_user_profile(User $user, UpdateUserRequest $request)
    {
        $user->update($request->validated());

        $user->syncRoles($request->get('role'));

        return redirect()->route('users.index')
            ->withSuccess(__('User updated successfully.'));
    }

    /**
     * Update auth user profile
     *
     * @param Request $request
     * @return void
     */
    public function update_my_profile(Request $request)
    {
        $this->validate($request, [
            'language'  => 'in:en,pt_BR',
            'theme' => 'in:Default,Default Dark,Big Light,Big Dark,Open Sidebar Light,Open Sidebar Dark,Hide Sidebar Light,Hide Sidebar Dark'
        ]);

        try {
            $user = Auth::user();
            $user->update($request->except(['role']));

            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $extension = $image->getClientOriginalExtension();
                $image_name = $user->id . "." . $extension;

                $destinationPath = public_path('/img/profiles');
                $image->move($destinationPath, $image_name);
                $user->update(['image' => $image_name]);
            }

            activity()
                ->causedBy(Auth::user()->id)
                ->event('updated')
                ->withProperties($request)
                ->tap(function (Activity $activity) use ($request) {
                    $activity->log_name = 'User';
                    $activity->subject_type = 'App\Models\User';
                    $activity->ip = $request->ip();
                })
                ->log('User ID: ' . $user->id . ' has been updated');

            Alert::success([__('global.alerts.success'), __('profile.alerts.profile_updated')]);

            return back();
        } catch (\Exception $e) {
            throw new ValidationException($e);

            Alert::error([__('global.alerts.error'), $e]);

            return back()
                ->withInput();
        }
    }

    /**
     * Change language of auth user
     *
     * @param Request $request
     * @param [type] $language
     * @return void
     */
    public function change_language(Request $request, $language)
    {
        $this->validate($request, [
            'language'  => 'in:en,pt_BR',
        ]);

        Auth::user()->update(['language' => $language]);

        Alert::success(__('global.alerts.success'), __('profile.alerts.language_updated'));
        return back();
    }

    /**
     * Will lock auth session
     *
     * @return void
     */
    public function lockscreen()
    {
        if (Auth::check()) {
            session(['lock-expires-at' => now()]);
            alert()->success(__('global.alerts.system_bloked'));
            return redirect()->route('login.locked');
        }
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests\StoreUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Http\Controllers\Controller;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\ValidationException;
use App\Models\User;
use RealRashid\SweetAlert\Facades\Alert;
use DataTables;
use Illuminate\Support\Facades\Hash;
use Spatie\Activitylog\Models\Activity;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth', '2fa']);
        $this->middleware('permission:users-list');
        $this->middleware('permission:users-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:users-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:users-change-status', ['only' => ['active', 'deactive']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.user.index');
    }

    /**
     * Create a new user
     *
     * @return void
     */
    public function create()
    {
        $roles = Role::latest()->get();
        return view('backend.user.create', compact('roles'));
    }

    /**
     * Edit user data
     *
     * @param User $user
     * @return void
     */
    public function edit(User $user)
    {
        $userRole = $user->roles->pluck('name')->toArray();
        $roles = Role::latest()->get();

        return view(
            'backend.user.edit',
            compact('user', 'userRole', 'roles')
        );
    }

    /**
     * Update user data
     *
     * @param User $user
     * @param UpdateUserRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function update(User $user, UpdateUserRequest $request)
    {
        $user->update($request->validated());

        $user->syncRoles($request->get('role'));

        return redirect()->route('users.index')
            ->withSuccess(__('User updated successfully.'));
    }

    /**
     * Store a newly created user
     *
     * @param User $user
     * @param StoreUserRequest $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserRequest $request)
    {
        try {
            $user = User::create([
                'name' => $request->input('name'),
                'email' => $request->input('email'),
                'password' => Hash::make($request->input('password')),
            ]);

            $user->syncRoles($request->get('role'));

            activity()
                ->causedBy(Auth::user()->id)
                ->event('created')
                ->withProperties($request)
                ->tap(function (Activity $activity) use ($request) {
                    $activity->log_name = 'User';
                    $activity->subject_type = 'App\Models\User';
                    $activity->ip = $request->ip();
                })
                ->log('User ID: ' . $user->id . ' has been created');

            Alert::success([__('global.alerts.success'), __('users.alerts.user_created')]);

            return redirect()->route('users.index');
        } catch (\Exception $e) {
            throw new ValidationException($e);

            Alert::error([__('global.alerts.error'), $e]);

            return back()
                ->withInput();
        }
    }

    /**
     * Active users can make login on system
     *
     * @param Request $request
     * @return void
     */
    public function active(Request $request)
    {
        $this->validate($request, [
            'status'  => 'in:0,1',
        ]);

        User::where('id', $request->id)->update(['status' => 1]);

        activity()
            ->causedBy(Auth::user()->id)
            ->event('activated')
            ->withProperties(['status' => 1])
            ->tap(function (Activity $activity) use ($request) {
                $activity->log_name = 'User';
                $activity->subject_type = 'App\Models\User';
                $activity->ip = $request->ip();
            })
            ->log('User ID: ' . $request->id . ' has been activated');

        Alert::success(__('global.alerts.success'), __('users.alerts.user_activated'));
        return back()->withInput();
    }

    /**
     * User deactivated can't make login on system
     *
     * @param Request $request
     * @return void
     */
    public function deactive(Request $request)
    {
        $this->validate($request, [
            'status'  => 'in:0,1',
        ]);

        User::where('id', $request->id)->update(['status' => 0]);

        activity()
            ->causedBy(Auth::user()->id)
            ->event('deactivated')
            ->withProperties(['status' => 0])
            ->tap(function (Activity $activity) use ($request) {
                $activity->log_name = 'User';
                $activity->subject_type = 'App\Models\User';
                $activity->ip = $request->ip();
            })
            ->log('User ID: ' . $request->id . ' has been deactivated');

        Alert::success(__('global.alerts.success'), __('users.alerts.user_deactivated'));
        return back()->withInput();
    }

    /**
     * List all users
     *
     * @param Request $request
     * @return void
     */
    public function getUsers(Request $request)
    {
        if ($request->ajax()) {

            $data = User::select(['id', 'name', 'email', 'phone', 'status', 'created_at'])->with('roles');

            return DataTables::of($data)
                ->addColumn('action', function ($row) {
                    if ($row->status == 1) {
                        $status_btn = '<a href="' . route("users.deactive", $row->id) . '" title="' . __('global.form.deactivate') . '" class="fa-solid fa-user-xmark" style="color: #dc3545"></a>';
                    } else {
                        $status_btn = '<a href="' . route("users.active", $row->id) . '"  title="' . __('global.form.activate') . '" class="fa-solid fa-user-check" style="color: #1e7e34"></a>';
                    }

                    $btn = '
                    <a href="' . route("user.profile", $row->id) . '" class="fa-solid fa-eye" title="' . __('global.form.view') . '" style="color: #0069d9; margin-right: 5px"></a>
                    <a href="' . route("users.edit", $row->id) . '" class="fa-solid fa-pen-to-square" title="' . __('global.form.edit') . '" style="color: #0069d9; margin-right: 5px"></a>
                    ' . $status_btn . '
                    ';

                    return $btn;
                })
                ->filter(function ($instance) use ($request) {
                    if ($request->get('status') == '0' || $request->get('status') == '1') {
                        $instance->where('status', $request->get('status'));
                    }
                    if (!empty($request->get('search'))) {
                        $instance->where(function ($w) use ($request) {
                            $search = $request->get('search');
                            $w->orWhere('name', 'LIKE', "%$search%")
                                ->orWhere('email', 'LIKE', "%$search%");
                        });
                    }
                })
                ->editColumn('name', function ($user) {
                    return '<a href="' . route('user.profile', $user->id) . '">' . $user->name . '</a>  ';
                })
                ->editColumn('status', function ($inquiry) {
                    if ($inquiry->status == 0)
                        return '<span class="badge bg-danger"> ' . __('global.status.deactivated') . '</span>';
                    if ($inquiry->status == 1)
                        return  '<span class="badge bg-success">' . __('global.status.activated') . '</span>';
                    return 'Cancel';
                })
                ->rawColumns(['action', 'name', 'status'])
                ->make(true);
        }
    }
}

resources/views/backend/user/profile/user_profile.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('profile.title'),
    'activePage' => 'profile',
    'activeNav' => '',
])

@section('styles')
	<!-- Select2 -->
	<link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.min.css') }}">
	<link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">
	<!-- summernote -->
	<link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.min.css') }}">
@endsection

@section('content')
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-3">
					<!-- Profile Image -->
					<div class="card card-primary card-outline">
						<div class="card-body box-profile">
							<div class="text-center">
								<img class="profile-user-img img-fluid img-circle"
									src="
                            @if ($user->image == 'profile_default.png') {{ asset('/img/profile_default.png') }}
                            @else
                            {{ asset('/img/profiles/' . $user->image) }} @endif
                            "
									alt="User profile picture">
							</div>
							<h3 class="profile-username text-center">{{ $user->name }}</h3>
							<p class="text-muted text-center">
								{{ $user->email }}
								<br>
								<small>ID: {{ $user->id }}</small>
							</p>

							<ul class="list-group list-group-unbordered mb-3">
								<li class="list-group-item">
									<b>
										{{ __('profile.user_status') }}
									</b>
									<a class="float-right">
										@if ($user->status == 1)
											<b class="text-success"> {{ __('global.status.activated') }} </b>
										@else
											<b class="text-danger"> {{ __('global.status.deactivated') }} </b>
										@endif
									</a>
								</li>
								<li class="list-group-item">
									<b>
										<a href=" {{ route('2fa') }} " style="color: inherit;">
											{{ __('profile.2fa_status') }}
										</a>
									</b>
									<a class="float-right">
										@if ($user->loginSecurity->google2fa_enable ?? '')
											<b class="text-success"> {{ __('global.status.activated') }} </b>
										@else
											<b class="text-danger"> {{ __('global.status.deactivated') }} </b>
										@endif
									</a>
								</li>
								<li class="list-group-item">
									<b>{{ __('global.role') }}</b>
									<a class="float-right" href="{{ route('roles.show', $user->roles->first()->id) }}">
										{{ $user->roles->first()->name }}
									</a>
								</li>
								<li class="list-group-item">
									<b>{{ __('profile.last_ip') }}</b>
									<a class="float-right">
										{{ $user->last_login_ip }}
									</a>
								</li>
								<li class="list-group-item">
									<b>{{ __('profile.last_login_at') }}</b>
									<a class="float-right">
										{{ $user->last_login_at }}
									</a>
								</li>
							</ul>
						</div>
						<!-- /.card-body -->
					</div>
					<!-- /.card -->

					<!-- About Me Box -->
					<div class="card card-primary">
						<div class="card-header">
							<h3 class="card-title">{{ __('profile.note_about_me') }}</h3>
						</div>
						<!-- /.card-header -->
						<div class="card-body">
							<strong><i class="fas fa-phone mr-1"></i> {{ __('global.phone') }}</strong>
							<p class="text-muted">
								{{ $user->phone }}
							</p>
							<hr>
							<strong><i class="fas fa-map-marker-alt mr-1"></i> {{ __('global.location') }}</strong>
							<p class="text-muted">{{ $user->location }}</p>
							<hr>
							<strong><i class="far fa-file-alt mr-1"></i> {{ __('global.notes') }}</strong>
							<p class="text-muted">{!! $user->notes !!}</p>
						</div>
						<!-- /.card-body -->
					</div>
					<!-- /.card -->
				</div>
				<!-- /.col -->
				<div class="col-md-9">
					<div class="card">
						<div class="card-body">
							Insert User activities here
						</div><!-- /.card-body -->
					</div>
					<!-- /.card -->
				</div>
				<!-- /.col -->
			</div>
			<!-- /.row -->
		</div><!-- /.container-fluid -->
	</section>
	<!-- /.content -->
@endsection

@section('scripts')
	<!-- Select2 -->
	<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>
	<!-- InputMask -->
	<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
	<script src="{{ asset('plugins/inputmask/jquery.inputmask.min.js') }}"></script>
	<!-- Summernote -->
	<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
	<!-- bs-custom-file-input -->
	<script src="{{ asset('plugins/bs-custom-file-input/bs-custom-file-input.min.js') }}"></script>
	<!-- Page specific script -->
	<script>
	 $(function() {
	  bsCustomFileInput.init();

	  //Initialize Select2 Elements
	  $('.select2').select2({
	   theme: 'bootstrap4'
	  })

	  // Summernote
	  $('#summernote').summernote()

	  // CodeMirror
	  CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
	   mode: "htmlmixed",
	   theme: "monokai"
	  });

	  $('[data-mask]').inputmask()
	 })
	</script>
@endsection