routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * FronEnd
 */
Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

/**
 * Unlock System
 */
Route::post('/login/locked', [App\Http\Controllers\Auth\LoginController::class, 'unlock'])
    ->name('login.unlock');

/**
 * Backend Routes
 */
Route::group(['middleware' => ['auth', 'check_user_status', 'check_user_single_session', 'auth.lock', '2fa', 'language']], function () {

    /**
     * Dashboard / Home
     */
    Route::get('/home', [App\Http\Controllers\Backend\HomeController::class, 'index'])
        ->name('home');

    /**
     * Lockscreen
     */
    Route::get('/login/locked', [App\Http\Controllers\Auth\LoginController::class, 'locked'])
        ->withoutMiddleware('auth.lock')->name('login.locked');

    /**
     * User
     */
    Route::controller(App\Http\Controllers\Backend\UserController::class)->group(function () {
        Route::prefix('users')->group(function () {
            Route::get('/', 'index')->name('users.index');
            Route::get('/create', 'create')->name('users.create');
            Route::get('/edit/{user}', 'edit')->name('users.edit');
            Route::post('/store', 'store')->name('users.store');
            Route::patch('/update/{user}', 'update')->name('users.update');
            Route::get('/getUsers', 'getUsers')->name('users.get');
            Route::get('/activate/{id}', 'active')->name('users.active');
            Route::get('/deactivate/{id}', 'deactive')->name('users.deactive');
        });
    });

    /**
     * Profile
     */
    Route::controller(App\Http\Controllers\Backend\ProfileController::class)->group(function () {
        Route::prefix('profile')->group(function () {
            Route::get('/{user}', 'user_profile')->name('user.profile');
            Route::patch('/my_profile/update/', 'update_my_profile')->name('profile.update');
        });
        Route::get('/lang/{language}', 'change_language')->name('lang.update');
        Route::get('/lockscreen', 'lockscreen')->name('users.lockscreen');
        Route::get('/my_profile/{user}', 'my_profile')->name('my.profile');
    });

    /**
     * System Settings
     */
    Route::controller(App\Http\Controllers\Backend\SystemSettingController::class)->group(function () {
        Route::prefix('system')->group(function () {
            Route::get('/settings', 'index')->name('system_settings');
            Route::get('/settings/edit', 'settings')->name('system_settings.edit');
            Route::post('/settings/edit', 'update')->name('system_settings.update');
        });
    });

    /**
     * Logs
     */
    Route::controller(App\Http\Controllers\Backend\LogController::class)->group(function () {
        Route::prefix('log')->group(function () {
            Route::get('/', 'index')->name('logs.index');
            Route::get('/getLogs', 'getLogs')->name('logs.get');
            Route::get('/clearLogs', 'clearLogs')->name('logs.clear');
        });
    });

    /**
     * 2FA
     */
    Route::controller(App\Http\Controllers\Backend\LoginSecurityController::class)->group(function () {
        Route::prefix('2fa')->group(function () {
            Route::any('/', 'show2faForm')->name('2fa');
            Route::post('/secret',  'generate2faSecret')->name('generate2faSecret');
            Route::post('/enable', 'enable2fa')->name('enable2fa');
            Route::post('/disable', 'disable2fa')->name('disable2fa');
        });
    });

    /**
     * Roles and permissions
     */
    Route::resource('/roles', App\Http\Controllers\RoleController::class);
    Route::resource('/permissions', App\Http\Controllers\PermissionController::class);

    /**
     * 2FA middleware
     */
    Route::post('/2faVerify', function () {
        return redirect(URL()->previous());
    })->name('2faVerify');
});

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
    <strong>Copyright © 2019 - {{date('Y')}} | <a href="https://github.com/gelbcke/" target="_blank">Gelbcke - LaraStart</a></strong>
    <div class="float-right d-none d-sm-inline-block">
        <b>v </b> {{config('app.version')}}
    </div>
</footer>

resources/views/layouts/partials/head.blade.php
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>{{ config('app.name') }} - {{ $namePage }}</title>

	<!-- Favicons -->
	<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('img/favicon/apple-touch-icon.png') }}">
	<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('img/favicon/favicon-32x32.png') }}">
	<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('img/favicon/favicon-16x16.png') }}">
	<link rel="manifest" href="{{ asset('img/favicon/site.webmanifest') }}">
	<link rel="mask-icon" href="{{ asset('img/favicon/safari-pinned-tab.svg') }}" color="#000000">
	<link rel="icon" type="image/x-icon" href="{{ asset('img/favicon/favicon.ico') }}">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="theme-color" content="#ffffff">

	<!-- Google Font: Source Sans Pro -->
	<link rel="stylesheet"
		href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
	<!-- Fonts -->
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

	<!-- Styles -->
	<link href="{{ asset('css/adminlte.min.css') }}" rel="stylesheet">
	<!-- overlayScrollbars -->
	<link rel="stylesheet" href="{{ asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">

	@yield('styles')

</head>

resources/views/layouts/partials/header.blade.php
				<!-- Content Header (Page header) -->
				<div class="content-header">
				<div class="container-fluid">
				<div class="row mb-2">
				<div class="col-sm-6">
				<h1 class="m-0">{{ $namePage }}</h1>
				</div><!-- /.col -->
				{{-- //
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{route('home')}}">Home</a></li>
                            <li class="breadcrumb-item active">{{ $namePage }}</li>
                        </ol>
                    </div>
                // --}}
				<!-- /.col -->
				</div><!-- /.row -->
				</div><!-- /.container-fluid -->
				</div>
				<!-- /.content-header -->

resources/views/layouts/partials/nav.blade.php
<!-- Navbar -->
<nav class="{{ $apply_theme->value('nav') }}">
	<!-- Left navbar links -->
	<ul class="navbar-nav">
		<li class="nav-item">
			<a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a href="{{ route('home') }}" class="nav-link">{{ __('layouts.home') }}</a>
		</li>
		<li class="nav-item d-none d-sm-inline-block">
			<a href="{{ route('my.profile', auth()->user()->id) }}" class="nav-link">{{ __('layouts.profile') }}</a>
		</li>
	</ul>
	<!-- Right navbar links -->
	<ul class="navbar-nav ml-auto">
		<li class="nav-item dropdown">
			<a class="nav-link" href="#" data-toggle="dropdown">
				{{ explode(' ', auth()->user()->name)[0] }}
			</a>
			<div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
				<a href="{{ route('my.profile', auth()->user()->id) }}" class="dropdown-item">
					{{ __('layouts.profile') }}
				</a>
				@can('users-list')
					<a href="{{ route('users.index') }}" class="dropdown-item">
						{{ __('layouts.users') }}
					</a>
				@endcan
				@can('logs-list')
					<a href="{{ route('logs.index') }}" class="dropdown-item">
						{{ __('layouts.logs') }}
					</a>
				@endcan
				@can('roles-list')
					<a href="{{ route('roles.index') }}" class="dropdown-item">
						{{ __('layouts.roles') }}
					</a>
				@endcan
				@can('permissions-list')
					<a href="{{ route('permissions.index') }}" class="dropdown-item">
						{{ __('layouts.permissions') }}
					</a>
				@endcan
				@can('settings-list')
					<a href="{{ route('system_settings') }}" class="dropdown-item">
						{{ __('layouts.system_settings') }}
					</a>
				@endcan
				<a class="dropdown-item" href="{{ route('logout') }}"
					onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
					{{ __('layouts.logout') }}
				</a>
				<form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
					@csrf
				</form>
			</div>
		</li>

		<li class="nav-item">
			<a class="nav-link" href="{{ route('users.lockscreen') }}" role="button" title="{{ __('auth.lock') }}">
				<i class="fas fa-lock"></i>
			</a>
		</li>
	</ul>
</nav>
<!-- /.navbar -->

resources/views/layouts/partials/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
	<!-- Brand Logo -->
	<a href="{{ route('home') }}" class="brand-link" style="color: inherit;">
		<img src="{{ asset('img/' . config('app.name') . 'Logo.png') }}" alt="{{ config('app.name') }} Logo"
			class="brand-image" style="opacity: .8">
		<span class="brand-text"><b>{{ config('app.name') }}</b></span>
	</a>

	<!-- Sidebar -->
	<div class="sidebar">
		<hr>
		<!-- Sidebar Menu -->
		<nav class="mt-2">
			<ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
				<!-- Add icons to the links using the .nav-icon class
															with font-awesome or any other icon font library -->
				<li class="nav-item">
					<a href="{{ route('home') }}" class="nav-link @if ($activePage == 'home') active @endif">
						<i class="nav-icon fas fa-home"></i>
						<p>
							{{ __('layouts.home') }}
						</p>
					</a>
				</li>
				<li class="nav-header">SYSTEM</li>

				@canany(['roles-list', 'permissions-list'])
					<li class="nav-item @if (in_array($activePage, ['roles', 'permissions'])) menu-open @endif">
						<a href="#" class="nav-link">
							<i class="fa-solid fa-shield-halved nav-icon"></i>
							<p>
								Security
								<i class="right fas fa-angle-left"></i>
							</p>
						</a>
						@can('roles-list')
							<ul class="nav nav-treeview">
								<li class="nav-item">
									<a href="{{ route('roles.index') }}" class="nav-link @if ($activePage == 'roles') active @endif">
										<i class="fa-solid fa-people-roof nav-icon"></i>
										<p>{{ __('roles.title') }}</p>
									</a>
								</li>
							</ul>
						@endcan
						@can('permissions-list')
							<ul class="nav nav-treeview">
								<li class="nav-item">
									<a href=" {{ route('permissions.index') }} " class="nav-link @if ($activePage == 'permissions') active @endif">
										<i class="fa-solid fa-user-shield nav-icon"></i>
										<p>{{ __('permissions.title') }}</p>
									</a>
								</li>
							</ul>
						@endcan
					</li>
				@endcan

				<li class="nav-header">DOCUMENTATION</li>










				<li class="nav-item">
					<a href="{{ url('/') }}" class="nav-link">
						<i class="nav-icon fas fa-cog"></i>
						<p>Back-end DOC</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="https://adminlte.io/docs/3.1/" target="_blank" class="nav-link">
						<i class="nav-icon fas fa-file"></i>
						<p>Front-end DOC</p>
					</a>
				</li>
				<li class="nav-header">MULTI LEVEL EXAMPLE</li>
				<li class="nav-item">
					<a href="#" class="nav-link">
						<i class="fas fa-circle nav-icon"></i>
						<p>Level 1</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="#" class="nav-link">
						<i class="nav-icon fas fa-circle"></i>
						<p>
							Level 1
							<i class="right fas fa-angle-left"></i>
						</p>
					</a>
					<ul class="nav nav-treeview">
						<li class="nav-item">
							<a href="#" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>Level 2</p>
							</a>
						</li>
						<li class="nav-item">
							<a href="#" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>
									Level 2
									<i class="right fas fa-angle-left"></i>
								</p>
							</a>
							<ul class="nav nav-treeview">
								<li class="nav-item">
									<a href="#" class="nav-link">
										<i class="far fa-dot-circle nav-icon"></i>
										<p>Level 3</p>
									</a>
								</li>
								<li class="nav-item">
									<a href="#" class="nav-link">
										<i class="far fa-dot-circle nav-icon"></i>
										<p>Level 3</p>
									</a>
								</li>
								<li class="nav-item">
									<a href="#" class="nav-link">
										<i class="far fa-dot-circle nav-icon"></i>
										<p>Level 3</p>
									</a>
								</li>
							</ul>
						</li>
						<li class="nav-item">
							<a href="#" class="nav-link">
								<i class="far fa-circle nav-icon"></i>
								<p>Level 2</p>
							</a>
						</li>
					</ul>
				</li>
				<li class="nav-item">
					<a href="#" class="nav-link">
						<i class="fas fa-circle nav-icon"></i>
						<p>Level 1</p>
					</a>
				</li>
				<li class="nav-header">LABELS</li>
				<li class="nav-item">
					<a href="#" class="nav-link">
						<i class="nav-icon far fa-circle text-danger"></i>
						<p class="text">Important</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="#" class="nav-link">
						<i class="nav-icon far fa-circle text-warning"></i>
						<p>Warning</p>
					</a>
				</li>
				<li class="nav-item">
					<a href="#" class="nav-link">
						<i class="nav-icon far fa-circle text-info"></i>
						<p>Informational</p>
					</a>
				</li>
			</ul>
		</nav>
		<!-- /.sidebar-menu -->
	</div>
	<!-- /.sidebar -->
</aside>