routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * FronEnd
 */
Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

/**
 * Unlock System
 */
Route::post('/login/locked', [App\Http\Controllers\Auth\LoginController::class, 'unlock'])
    ->name('login.unlock');

/**
 * Backend Routes
 */
Route::group(['middleware' => ['auth', 'check_user_status', 'check_user_single_session', 'auth.lock', '2fa', 'language']], function () {

    /**
     * Dashboard / Home
     */
    Route::get('/home', [App\Http\Controllers\Backend\HomeController::class, 'index'])
        ->name('home');

    /**
     * Lockscreen
     */
    Route::get('/login/locked', [App\Http\Controllers\Auth\LoginController::class, 'locked'])
        ->withoutMiddleware('auth.lock')->name('login.locked');

    /**
     * User
     */
    Route::controller(App\Http\Controllers\Backend\UserController::class)->group(function () {
        Route::prefix('users')->group(function () {
            Route::get('/', 'index')->name('users.index');
            Route::get('/create', 'create')->name('users.create');
            Route::get('/edit/{user}', 'edit')->name('users.edit');
            Route::post('/store', 'store')->name('users.store');
            Route::patch('/update/{user}', 'update')->name('users.update');
            Route::get('/getUsers', 'getUsers')->name('users.get');
            Route::get('/activate/{id}', 'active')->name('users.active');
            Route::get('/deactivate/{id}', 'deactive')->name('users.deactive');
        });
    });

    /**
     * Profile
     */
    Route::controller(App\Http\Controllers\Backend\ProfileController::class)->group(function () {
        Route::prefix('profile')->group(function () {
            Route::get('/{user}', 'user_profile')->name('user.profile');
            Route::patch('/my_profile/update/', 'update_my_profile')->name('profile.update');
        });
        Route::get('/lang/{language}', 'change_language')->name('lang.update');
        Route::get('/lockscreen', 'lockscreen')->name('users.lockscreen');
        Route::get('/my_profile/{user}', 'my_profile')->name('my.profile');
    });

    /**
     * System Settings
     */
    Route::controller(App\Http\Controllers\Backend\SystemSettingController::class)->group(function () {
        Route::prefix('system')->group(function () {
            Route::get('/settings', 'index')->name('system_settings');
            Route::get('/settings/edit', 'settings')->name('system_settings.edit');
            Route::post('/settings/edit', 'update')->name('system_settings.update');
        });
    });

    /**
     * Logs
     */
    Route::controller(App\Http\Controllers\Backend\LogController::class)->group(function () {
        Route::prefix('log')->group(function () {
            Route::get('/', 'index')->name('logs.index');
            Route::get('/getLogs', 'getLogs')->name('logs.get');
            Route::get('/clearLogs', 'clearLogs')->name('logs.clear');
        });
    });

    /**
     * 2FA
     */
    Route::controller(App\Http\Controllers\Backend\LoginSecurityController::class)->group(function () {
        Route::prefix('2fa')->group(function () {
            Route::any('/', 'show2faForm')->name('2fa');
            Route::post('/secret',  'generate2faSecret')->name('generate2faSecret');
            Route::post('/enable', 'enable2fa')->name('enable2fa');
            Route::post('/disable', 'disable2fa')->name('disable2fa');
        });
    });

    /**
     * Roles and permissions
     */
    Route::resource('/roles', App\Http\Controllers\RoleController::class);
    Route::resource('/permissions', App\Http\Controllers\PermissionController::class);

    /**
     * 2FA middleware
     */
    Route::post('/2faVerify', function () {
        return redirect(URL()->previous());
    })->name('2faVerify');
});

app/Models/Permission.php
<?php

namespace App\Models;

use Spatie\Permission\Models\Permission as SpatiePermission;
use App\Traits\Uuids;

class Permission extends SpatiePermission
{
    use Uuids;

    protected $primaryKey = 'id';

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * The "type" of the primary key ID.
     *
     * @var string
     */
    protected $keyType = 'string';

    /**
     * Default Permissions of the Application.
     */
    public static function defaultPermissions()
    {
        return [
            'users-list',
            'users-create',
            'users-edit',
            'users-change-status',

            'profiles-view-all',
            'profiles-view-own',
            'profiles-edit-all',
            'profiles-edit-own',

            'roles-list',
            'roles-create',
            'roles-edit',
            'roles-delete',

            'permissions-list',
            'permissions-create',
            'permissions-edit',
            'permissions-delete',

            'logs-list',
            'logs-clear',

            'settings-list',
            'settings-update',
        ];
    }

    /**
     * Name should be lowercase.
     *
     * @param  string  $value  Name value
     */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtolower($value);
    }
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Permission;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;
use Spatie\Activitylog\Models\Activity;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:permissions-list');
        $this->middleware('permission:permissions-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:permissions-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:permissions-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $permissions = Permission::all();

        return view('permissions.index', [
            'permissions' => $permissions
        ]);
    }

    /**
     * Show form for creating permissions
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id' => 'string',
            'name' => 'required|unique:users,name'
        ]);

        $permission = Permission::create($request->only('name'));

        activity()
            ->causedBy(Auth::user()->id)
            ->event('created')
            ->withProperties($request)
            ->tap(function (Activity $activity) use ($request) {
                $activity->log_name = 'Permission';
                $activity->subject_type = 'App\Models\Permission';
                $activity->ip = $request->ip();
            })
            ->log('New permission ' . $permission->name . ' created!');

        Alert::success(__('global.alerts.success'), 'Permission ' . $permission->name . ' created successfully.');

        return redirect()->route('permissions.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Permission  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Permission $permission)
    {
        return view('permissions.edit', [
            'permission' => $permission
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Permission  $permission
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Permission $permission)
    {
        $request->validate([
            'name' => 'required|unique:permissions,name,' . $permission->id
        ]);

        $permission->update($request->only('name'));

        activity()
            ->causedBy(Auth::user()->id)
            ->event('updated')
            ->withProperties($request)
            ->tap(function (Activity $activity) use ($request) {
                $activity->log_name = 'Permission';
                $activity->subject_type = 'App\Models\Permission';
                $activity->ip = $request->ip();
            })
            ->log('Permission ' . $permission->name . ' was updated!');

        Alert::success(__('global.alerts.success'), 'Permission ' . $permission->name . ' updated successfully.');

        return redirect()->route('permissions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Permission $permission, Request $request)
    {
        $permission->delete();

        activity()
            ->causedBy(Auth::user()->id)
            ->event('deleted')
            ->withProperties($request)
            ->tap(function (Activity $activity) use ($request) {
                $activity->log_name = 'Permission';
                $activity->subject_type = 'App\Models\Permission';
                $activity->ip = $request->ip();
            })
            ->log('Permission ' . $permission->name . ' was deleted!');

        Alert::success(__('global.alerts.success'), 'Permission ' . $permission->name . ' deleted successfully.');

        return redirect()->route('permissions.index');
    }
}

resources/views/permissions/create.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('permissions.title'),
    'activePage' => 'permissions',
    'activeNav' => '',
])

@section('content')
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<div class="card-title">
								<h3 class="card-title">{{ __('global.form.create') . ' ' . __('permissions.title') }}</h3>
								<br>
								<small>{{ __('permissions.create.description') }}</small>
							</div>
						</div>
						<div class="card-body">
							<form method="POST" action="{{ route('permissions.store') }}">
								@csrf
								<div class="mb-3">
									<label for="name" class="form-label">{{ __('global.name') . ' ' . __('permissions.title') }}</label>
									<input value="{{ old('name') }}" type="text" class="form-control" name="name" placeholder="Name"
										required>

									@if ($errors->has('name'))
										<span class="text-danger text-left">{{ $errors->first('name') }}</span>
									@endif
								</div>
								<div class="row">
									<!-- /.col -->
									<div class="col-3">
										<a href="{{ url()->previous() }}" class="btn btn-default btn-block">{{ __('global.form.go_back') }}</a>
									</div>
									<div class="col-9">
										<button type="submit"
											class="btn btn-primary btn-block">{{ __('global.form.save') . ' ' . __('permissions.title') }}
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

resources/views/permissions/edit.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('permissions.title'),
    'activePage' => 'permissions',
    'activeNav' => '',
])

@section('content')
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<div class="card-title">
								<h3 class="card-title">{{ __('global.form.edit') . ' ' . __('permissions.title') }}</h3>
								<br>
								<small>{!! __('permissions.editing_permission', ['name' => '<b>' . $permission->name . '</b>']) !!} </small>
							</div>
						</div>
						<div class="card-body">
							<form method="POST" action="{{ route('permissions.update', $permission->id) }}">
								@method('patch')
								@csrf
								<div class="mb-3">
									<label for="name" class="form-label">{{ __('global.name') . ' ' . __('permissions.title') }}</label>
									<input value="{{ $permission->name }}" type="text" class="form-control" name="name"
										placeholder="{{ __('global.name') . ' ' . __('permissions.title') }}" required>

									@if ($errors->has('name'))
										<span class="text-danger text-left">{{ $errors->first('name') }}</span>
									@endif
								</div>
								<div class="row">
									<!-- /.col -->
									<div class="col-3">
										<a href="{{ url()->previous() }}" class="btn btn-default btn-block">{{ __('global.form.go_back') }}</a>
									</div>
									<div class="col-9">
										<button type="submit"
											class="btn btn-primary btn-block">{{ __('global.form.update') . ' ' . __('permissions.title') }}</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

resources/views/permissions/index.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('permissions.title'),
    'activePage' => 'permissions',
    'activeNav' => '',
])

@section('content')
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<div class="card-title">
								<h3 class="card-title">{{ __('permissions.title') }}</h3>
								<br>
								<small>{{ __('permissions.description') }}</small>
							</div>
							<div class="card-tools">
								<a href="{{ route('permissions.create') }}"
									class="btn btn-block btn-primary btn-xs">{{ __('global.form.create') }}
								</a>
							</div>
						</div>
						<table class="table-striped table-sm table">
							<thead>
								<tr>
									<th width="30%">{{ __('global.name') }}</th>
									<th>Guard</th>
									<th colspan="3" width="1%"></th>
								</tr>
							</thead>
							<tbody>
								@foreach ($permissions as $permission)
									<tr>
										<td>{{ $permission->name }}</td>
										<td>{{ $permission->guard_name }}</td>
										<td>
											<a href="{{ route('permissions.edit', $permission->id) }}" class="btn btn-xs">
												<i class="fa-solid fa-pen-to-square"></i>
											</a>
										</td>
										<td>
											<form method="POST" action="{{ route('permissions.destroy', $permission->id) }}">
												{{ csrf_field() }}
												{{ method_field('DELETE') }}
												<button type="submit" class="btn delete-permission btn-xs">
													<i class="fa-solid fa-trash text-danger"></i>
												</button>
											</form>
										</td>
									</tr>
								@endforeach
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

@section('scripts')
	<script>
	 $('.delete-permission').click(function(e) {
	  e.preventDefault() // Don't post the form, unless confirmed
	  if (confirm('Are you sure?')) {
	   // Post the form
	   $(e.target).closest('form').submit() // Post the surrounding form
	  }
	 });
	</script>
@endsection