routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Redirect;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * FronEnd
 */
Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

/**
 * Unlock System
 */
Route::post('/login/locked', [App\Http\Controllers\Auth\LoginController::class, 'unlock'])
    ->name('login.unlock');

/**
 * Backend Routes
 */
Route::group(['middleware' => ['auth', 'check_user_status', 'check_user_single_session', 'auth.lock', '2fa', 'language']], function () {

    /**
     * Dashboard / Home
     */
    Route::get('/home', [App\Http\Controllers\Backend\HomeController::class, 'index'])
        ->name('home');

    /**
     * Lockscreen
     */
    Route::get('/login/locked', [App\Http\Controllers\Auth\LoginController::class, 'locked'])
        ->withoutMiddleware('auth.lock')->name('login.locked');

    /**
     * User
     */
    Route::controller(App\Http\Controllers\Backend\UserController::class)->group(function () {
        Route::prefix('users')->group(function () {
            Route::get('/', 'index')->name('users.index');
            Route::get('/create', 'create')->name('users.create');
            Route::get('/edit/{user}', 'edit')->name('users.edit');
            Route::post('/store', 'store')->name('users.store');
            Route::patch('/update/{user}', 'update')->name('users.update');
            Route::get('/getUsers', 'getUsers')->name('users.get');
            Route::get('/activate/{id}', 'active')->name('users.active');
            Route::get('/deactivate/{id}', 'deactive')->name('users.deactive');
        });
    });

    /**
     * Profile
     */
    Route::controller(App\Http\Controllers\Backend\ProfileController::class)->group(function () {
        Route::prefix('profile')->group(function () {
            Route::get('/{user}', 'user_profile')->name('user.profile');
            Route::patch('/my_profile/update/', 'update_my_profile')->name('profile.update');
        });
        Route::get('/lang/{language}', 'change_language')->name('lang.update');
        Route::get('/lockscreen', 'lockscreen')->name('users.lockscreen');
        Route::get('/my_profile/{user}', 'my_profile')->name('my.profile');
    });

    /**
     * System Settings
     */
    Route::controller(App\Http\Controllers\Backend\SystemSettingController::class)->group(function () {
        Route::prefix('system')->group(function () {
            Route::get('/settings', 'index')->name('system_settings');
            Route::get('/settings/edit', 'settings')->name('system_settings.edit');
            Route::post('/settings/edit', 'update')->name('system_settings.update');
        });
    });

    /**
     * Logs
     */
    Route::controller(App\Http\Controllers\Backend\LogController::class)->group(function () {
        Route::prefix('log')->group(function () {
            Route::get('/', 'index')->name('logs.index');
            Route::get('/getLogs', 'getLogs')->name('logs.get');
            Route::get('/clearLogs', 'clearLogs')->name('logs.clear');
        });
    });

    /**
     * 2FA
     */
    Route::controller(App\Http\Controllers\Backend\LoginSecurityController::class)->group(function () {
        Route::prefix('2fa')->group(function () {
            Route::any('/', 'show2faForm')->name('2fa');
            Route::post('/secret',  'generate2faSecret')->name('generate2faSecret');
            Route::post('/enable', 'enable2fa')->name('enable2fa');
            Route::post('/disable', 'disable2fa')->name('disable2fa');
        });
    });

    /**
     * Roles and permissions
     */
    Route::resource('/roles', App\Http\Controllers\RoleController::class);
    Route::resource('/permissions', App\Http\Controllers\PermissionController::class);

    /**
     * 2FA middleware
     */
    Route::post('/2faVerify', function () {
        return redirect(URL()->previous());
    })->name('2faVerify');
});

app/Models/Role.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Spatie\Permission\Models\Role as SpatieRole;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Role extends SpatieRole
{
    use HasFactory, Uuids;

    protected $primaryKey = 'id';
    public $incrementing = false;

    /**
     * Name should be lowercase.
     *
     * @param  string  $value  Name value
     */
    public function setNameAttribute($value)
    {
        $this->attributes['name'] = strtolower($value);
    }
}

app/Http/Controllers/RoleController.php
<?php


namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\Permission;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;
use Spatie\Activitylog\Models\Activity;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:roles-list');
        $this->middleware('permission:roles-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:roles-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:roles-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::with('permissions')->get();
        return view('roles.index', compact('roles'));
        /*
        $roles = Role::orderBy('id', 'DESC')->paginate(5);

        return view('roles.index', compact('roles'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
            */
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::get();
        return view('roles.create', compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);

        try {
            $role = Role::create(['name' => $request->get('name')]);
            $role->syncPermissions($request->get('permission'));

            activity()
                ->causedBy(Auth::user()->id)
                ->event('created')
                ->withProperties($request)
                ->tap(function (Activity $activity) use ($request) {
                    $activity->log_name = 'Role';
                    $activity->subject_type = 'App\Models\Role';
                    $activity->ip = $request->ip();
                })
                ->log('Role ' . $role->name . ' created!');

            Alert::success(__('global.alerts.success'), 'Role created successfully');

            return redirect()->route('roles.index');
        } catch (\Exception $e) {
            Alert::warning('Error: ' . $e);
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        $role = $role;
        $rolePermissions = $role->permissions;

        return view('roles.show', compact('role', 'rolePermissions'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $role = $role;
        $rolePermissions = $role->permissions->pluck('name')->toArray();
        $permissions = Permission::get();

        return view('roles.edit', compact('role', 'rolePermissions', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Role $role, Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);

        $role->update($request->only('name'));

        $role->syncPermissions($request->get('permission'));

        activity()
            ->causedBy(Auth::user()->id)
            ->event('updated')
            ->withProperties($request)
            ->tap(function (Activity $activity) use ($request) {
                $activity->log_name = 'Role';
                $activity->subject_type = 'App\Models\Role';
                $activity->ip = $request->ip();
            })
            ->log('Role ' . $role->name . ' was updated!');

        Alert::success(__('global.alerts.success'), 'Role updated successfully');

        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role, Request $request)
    {
        $role->delete();

        activity()
            ->causedBy(Auth::user()->id)
            ->event('deleted')
            ->withProperties($request)
            ->tap(function (Activity $activity) use ($request) {
                $activity->log_name = 'Role';
                $activity->subject_type = 'App\Models\Role';
                $activity->ip = $request->ip();
            })
            ->log('Role ' . $role->name . ' was deleted!');

        Alert::success(__('global.alerts.success'), 'Role deleted successfully!');

        return redirect()->route('roles.index');
    }
}

resources/views/roles/create.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('roles.title'),
    'activePage' => 'roles',
    'activeNav' => '',
])
@section('content')
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<div class="card-title">
								<h3 class="card-title">{{ __('roles.create.title') }}</h3>
								<br>
								<small>{{ __('roles.create.description') }}</small>
							</div>
						</div>
						<div class="card-body">
							@if (count($errors) > 0)
								<div class="alert alert-danger">
									<strong>Whoops!</strong> There were some problems with your input.<br><br>
									<ul>
										@foreach ($errors->all() as $error)
											<li>{{ $error }}</li>
										@endforeach
									</ul>
								</div>
							@endif
							<form method="POST" action="{{ route('roles.store') }}">
								@csrf
								<div class="mb-3">
									<label for="name" class="form-label">{{ __('roles.role_name') }}</label>
									<input value="{{ old('name') }}" type="text" class="form-control" name="name" placeholder="Name"
										required>
								</div>
								<label for="permissions" class="form-label">{{ __('roles.assign_permissions') }}</label>
								<table class="table-striped table">
									<thead>
										<th scope="col" width="1%"><input type="checkbox" name="all_permission"></th>
										<th scope="col" width="20%">{{ __('permissions.title') }}</th>
										<th scope="col" width="1%">Guard</th>
									</thead>
									@foreach ($permissions as $permission)
										<tr>
											<td>
												<input type="checkbox" name="permission[{{ $permission->name }}]" value="{{ $permission->name }}"
													class='permission'>
											</td>
											<td>{{ $permission->name }}</td>
											<td>{{ $permission->guard_name }}</td>
										</tr>
									@endforeach
								</table>
								<div class="row">
									<!-- /.col -->
									<div class="col-3">
										<a href="{{ url()->previous() }}" class="btn btn-default btn-block">
											{{ __('global.form.go_back') }}
										</a>
									</div>
									<div class="col-9">
										<button type="submit" class="btn btn-primary btn-block">
											{{ __('global.form.save') . ' ' . __('roles.role') }}
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

@section('scripts')
	<script type="text/javascript">
	 $(document).ready(function() {
	  $('[name="all_permission"]').on('click', function() {

	   if ($(this).is(':checked')) {
	    $.each($('.permission'), function() {
	     $(this).prop('checked', true);
	    });
	   } else {
	    $.each($('.permission'), function() {
	     $(this).prop('checked', false);
	    });
	   }

	  });
	 });
	</script>
@endsection

resources/views/roles/edit.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('roles.title'),
    'activePage' => 'roles',
    'activeNav' => '',
])
@section('content')
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<div class="card-title">
								<h3 class="card-title">{!! __('roles.edit.title', ['name' => '<b>' . $role->name . '</b>']) !!}</h3>
								<br>
								<small>{{ __('roles.edit.description') }}</small>
							</div>
						</div>
						<div class="card-body">

							@if (count($errors) > 0)
								<div class="alert alert-danger">
									<strong>Whoops!</strong> There were some problems with your input.<br><br>
									<ul>
										@foreach ($errors->all() as $error)
											<li>{{ $error }}</li>
										@endforeach
									</ul>
								</div>
							@endif

							<form method="POST" action="{{ route('roles.update', $role->id) }}">
								@method('patch')
								@csrf
								<div class="mb-3">
									<label for="name" class="form-label">{{ __('roles.role_name') }}</label>
									<input value="{{ $role->name }}" type="text" class="form-control" name="name" placeholder="Name"
										required>
								</div>

								<label for="permissions" class="form-label">{{ __('roles.assign_permissions') }}</label>

								<table class="table-striped table">
									<thead>
										<th scope="col" width="1%"><input type="checkbox" name="all_permission"></th>
										<th scope="col" width="20%">Name</th>
										<th scope="col" width="1%">Guard</th>
									</thead>

									@foreach ($permissions as $permission)
										<tr>
											<td>
												<input type="checkbox" name="permission[{{ $permission->name }}]" value="{{ $permission->name }}"
													class='permission' {{ in_array($permission->name, $rolePermissions) ? 'checked' : '' }}>
											</td>
											<td>{{ $permission->name }}</td>
											<td>{{ $permission->guard_name }}</td>
										</tr>
									@endforeach
								</table>
								<div class="row">
									<!-- /.col -->
									<div class="col-3">
										<a href="{{ url()->previous() }}" class="btn btn-default btn-block">{{ __('global.form.go_back') }}</a>
									</div>
									<div class="col-9">
										<button type="submit" class="btn btn-primary btn-block">{{ __('roles.edit.update_role') }}</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

@section('scripts')
	<script type="text/javascript">
	 $(document).ready(function() {
	  $('[name="all_permission"]').on('click', function() {

	   if ($(this).is(':checked')) {
	    $.each($('.permission'), function() {
	     $(this).prop('checked', true);
	    });
	   } else {
	    $.each($('.permission'), function() {
	     $(this).prop('checked', false);
	    });
	   }

	  });
	 });
	</script>
@endsection

resources/views/roles/index.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('roles.title'),
    'activePage' => 'roles',
    'activeNav' => '',
])
@section('content')
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<div class="card-title">
								<h3 class="card-title">{{ __('roles.title') }}</h3>
								<br>
								<small>{{ __('roles.description') }} </small>
							</div>
							<div class="card-tools">
								<a href="{{ route('roles.create') }}" class="btn btn-block btn-primary btn-xs">{{ __('global.form.create') }}
								</a>
							</div>
						</div>

						<table class="table-striped table">
							<tr>
								<th>{{ __('roles.role_name') }}</th>
								<th width="3%" colspan="3">{{ __('global.action') }}</th>
							</tr>
							@foreach ($roles as $role)
								<tr>
									<td>{{ $role->name }}</td>
									<td>
										<a class="btn btn-xs" href="{{ route('roles.show', $role->id) }}">
											<i class="fa-solid fa-eye"></i>
										</a>
									</td>
									<td>
										<a class="btn btn-xs" href="{{ route('roles.edit', $role->id) }}">
											<i class="fa-solid fa-pen-to-square"></i>
										</a>
									</td>
									<td>
										<form method="POST" action="{{ route('roles.destroy', $role->id) }}">
											{{ csrf_field() }}
											{{ method_field('DELETE') }}

											<button type="submit" class="btn delete-role btn-xs">
												<i class="fa-solid fa-trash text-danger"></i>
											</button>
										</form>
									</td>
								</tr>
							@endforeach
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection

@section('scripts')
	<script>
	 $('.delete-role').click(function(e) {
	  e.preventDefault() // Don't post the form, unless confirmed
	  if (confirm('Are you sure?')) {
	   // Post the form
	   $(e.target).closest('form').submit() // Post the surrounding form
	  }
	 });
	</script>
@endsection

resources/views/roles/show.blade.php
@extends('layouts.app', [
    'class' => 'sidebar-mini ',
    'namePage' => __('roles.title'),
    'activePage' => 'roles',
    'activeNav' => '',
])
@section('content')
	<!-- Main content -->
	<section class="content">
		<div class="container-fluid">
			<div class="row">
				<div class="col-12">
					<div class="card">
						<div class="card-header">
							<div class="card-title">
								<h3 class="card-title"> {!! __('roles.show.role_name', ['name' => '<b>' . ucfirst($role->name) . '</b>']) !!} </h3>
								<br>
								<small>{{ __('roles.show.description') }}</small>
							</div>
						</div>
						<table class="table-striped table">
							<thead>
								<th scope="col" width="20%">{{ __('permissions.title') }}</th>
								<th scope="col" width="1%">Guard</th>
							</thead>

							@foreach ($rolePermissions as $permission)
								<tr>
									<td>{{ $permission->name }}</td>
									<td>{{ $permission->guard_name }}</td>
								</tr>
							@endforeach

						</table>
					</div>
					<div class="card-body">
						<div class="row">
							<!-- /.col -->
							<div class="col-12">
								<a href="{{ url()->previous() }}" class="btn btn-default btn-block">{{ __('global.form.go_back') }}</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection